### ISSUE TITLE
Menu Connection/Register/Logout

### ISSUE THREAD

**Issue by ThomasEscorne** [Msisou27/PFF_frontend_nounou#3]
Le menu de connection en haut à droite est présent que l'user soit connecté ou pas ce qui porte à confusion.
Si l'user est connecté la seule option doit être Logout
Si l'user n'est pas connecté les options doivent être Register et Log in

**Comment by Msisou27** [comment]
les menus sont mis a jour: 
Logout si user connecté et seulement register et login si  non connecté.
